// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ZDrive.Models
{
    public partial class ReservedSeat
    {
        [Key]
        [Column("RouteID")]
        public int RouteId { get; set; }
        [Key]
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(RouteId))]
        [InverseProperty("ReservedSeats")]
        public virtual Route Route { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("ReservedSeats")]
        public virtual User User { get; set; }
    }
}