// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ZDrive.Models
{
    [Table("Car")]
    public partial class Car
    {
        [Key]
        [StringLength(7, MinimumLength = 7)]
        [Display(Name = "License plate")]
        [Required]
        public string Licenseplate { get; set; }
        [Display(Name = "Number of passenger seats")]
        [Range(1, 5)]
        [Required]
        public int NumberOfSeats { get; set; }
        public int AvailableSeats { get; set; }
        [Display(Name = "Size of car")]
        [Required]
        public string SizeOfCar { get; set; }
        [Column("UserID")]
        [Required]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Cars")]
        public virtual User User { get; set; }
    }
}