// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ZDrive.Models
{
    [Table("Car")]
    public partial class Car
    {
        [Key]
        [StringLength(50)]
        public string Licenseplate { get; set; }
        public int NumberOfSeats { get; set; }
        public int AvailableSeats { get; set; }
        public string SizeOfCar { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Cars")]
        public virtual User User { get; set; }
    }
}