// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ZDrive.Models
{
    public partial class Route
    {
        public Route()
        {
            Stops = new HashSet<Stop>();
        }

        [Key]
        [Column("RouteID")]
        public int RouteId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Routes")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(Stop.Route))]
        public virtual ICollection<Stop> Stops { get; set; }
    }
}