// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ZDrive.Models
{
    public partial class Stop
    {
        [Key]
        [Column("StopID")]
        public int StopId { get; set; }
        [Required]
        [StringLength(50)]
        public string StopAddress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StopTimestamp { get; set; }
        [Column("RouteID")]
        public int? RouteId { get; set; }

        [ForeignKey(nameof(RouteId))]
        [InverseProperty("Stops")]
        public virtual Route Route { get; set; }
    }
}